### ISSUE TITLE
Error importing quickship.obj

### ISSUE THREAD

**Issue by mamarilmanson** [flipcoder/bouncingship#1]
![importerror](https://cloud.githubusercontent.com/assets/3820189/12712596/5cdda67e-c904-11e5-9390-81725d681780.png)

**Comment by flipcoder** [comment]
The textures are using absolute paths (like E:\etc).  Qor ignores it so it still works.  I think the exporter that my artist is using is doing that so I'll see if he can fix.

**Comment by flipcoder** [comment]
Fixed: https://github.com/flipcoder/bouncingship/commit/133927ba7a472d564a6c0384a6eacc16a44dee0f
